// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteTodo struct {
	ID string `json:"id"`
}

type Mutation struct {
}

type NewTodo struct {
	Text string `json:"text"`
}

type Query struct {
}

type Todo struct {
	Text      string `json:"text"`
	Completed bool   `json:"completed"`
}

type TodoID struct {
	ID string `json:"id"`
}

type UpdateTodo struct {
	ID        string `json:"id"`
	Text      string `json:"text"`
	Completed bool   `json:"completed"`
}
